### ISSUE TITLE
I already have a webrtc server with me and I want to use my server in place of the server provided in the plugin

### ISSUE THREAD

**Issue by zainzeus** [because-why-not/awrtc_browser#11]
Great asset, really very helpful!
Just minor thing which is I am unable to change this server to my own, whenever I change the link in the prefab, it unable to get connect, can you please describe me how to use my own server as it is.
This is my example code:
![image](https://user-images.githubusercontent.com/38684806/111860154-a6549880-896b-11eb-8ea4-a6ebb6d4e71b.png)

**Comment by devluz** [comment]
Check if you got the protocols right and ports right. You usually can't have a WS url and a WSS url both using the same port as in the code show above. I suspect your uSecrueSignalingUrl is likely incorrect. 

For WebGL the ChatApp will default you using "uSecureSignalingUrl" and expects "wss" because this is required by Chrome (the whole page must be secure using only https and wss). 

Another pitfall: Make sure that the actual GameObject has the correct URL as well. Unity might overwrite what you set as value in a public string. 

Best to check with the log of the CallApp to check if the values you set are actually used. It should print it to the browser log.
