### ISSUE TITLE
Unity usage

### ISSUE THREAD

**Issue by Dorianc4** [because-why-not/awrtc_browser#4]
I'm working with your unity plugin but i need to do my own signaling service  but I have none experience with TypeScript, can you explain me how can i use this browser as a signaling address for your unity plugin? Thanks.

**Comment by devluz** [comment]
The signaling server is at https://github.com/because-why-not/awrtc_signaling . awrtc_browser is a client side application so it won't be able to act as a signaling server. You won't need any typescript experience for the basic setup. It will build to java script and can run like a server side application. You find a tutorial on the page or can follow the tutorial at https://www.because-why-not.com/webrtc/tutorials-server-side/#Scenarios_Tutorials if you have the Unity version.
